### ISSUE TITLE
Backspace Button

### ISSUE THREAD

**Issue by WhoisBsa** [gazlaws-dev/codeboard#56] opened 2019-02-01 18:16 UTC
I think the design of the backspace button not is cool. Maybe if you change for a normal button it would be better

**Comment by sonakollarova5** [comment] 2019-10-07 15:38
Can I work on this issue?

**Comment by WhoisBsa** [comment] 2019-10-07 17:41
Yes!!!

**Comment by peterekepeter** [comment] 2019-10-24 20:30
There might be a practical solution to this, there is a symbol in unicode that was made for this 
![image](https://user-images.githubusercontent.com/7863124/67522846-295dba80-f6b6-11e9-9bed-2fbbb419d8ad.png)

**Comment by WhoisBsa** [comment] 2019-10-25 03:32
That's what I'm Talking about!!! Good job @peterekepeter!

**Comment by peterekepeter** [comment] 2019-10-28 09:57
@sonya323 if you come up with anything better, let me know though.

**Comment by gazlaws-dev** [comment] 2020-04-19 08:16
Duplicate of #13

**Closed by gazlaws-dev** 2020-04-19 08:16 UTC
Labels: UI, good first issue
