### ISSUE TITLE
Feature Request : Button to go back to previous keyboard 

### ISSUE THREAD

**Issue by chagai95** [gazlaws-dev/codeboard#64] opened 2019-11-12 22:58 UTC
This would be super useful because the keyboard is not all that good and you just wanna use it for certain things and quickly go back to the last keyboard.

**Comment by Ximzend57** [comment] 2019-12-12 16:08
You can switch to a different keyboard by holding the Space key.

**Comment by chagai95** [comment] 2019-12-12 16:12
I know but that still takes time, a button to go back to the previous keyboard would make it easier

**Comment by gazlaws-dev** [comment] 2020-04-19 08:14
Duplicate of #47

**Closed by gazlaws-dev** 2020-04-19 08:14 UTC
